buildscript {
    repositories {
        maven {
            url 'http://localhost:8080/snapshots'
        }

        mavenCentral()
    }

    dependencies {
        classpath 'info.gianlucacosta.aurora:aurora:10.0.0-SNAPSHOT'
    }
}

plugins {
    id 'scala'
    id 'maven'
    id 'org.openjfx.javafxplugin' version '0.0.10'
}

apply plugin: 'info.gianlucacosta.aurora'

group = 'info.gianlucacosta.helios'
archivesBaseName = 'helios-fx'
version = '7.0.0-SNAPSHOT'

description = 'Library of ScalaFX utilities'

dependencies {
    generatedCompile 'org.scala-lang:scala-library:2.13.14'

    compile 'org.scala-lang:scala-library:2.13.14'
    compile 'org.scalafx:scalafx_2.13:12.0.2-R18'

    compile 'info.gianlucacosta.helios:helios-core:7.0.0-SNAPSHOT'
}

aurora {
    gitHubUser = 'giancosta86'

    author {
        name = 'Gianluca Costa'
        email = 'gianluca@gianlucacosta.info'
        url = 'http://gianlucacosta.info/'
    }

    mavenDeploy {
        url = 'http://localhost:8080/snapshots'
    }
}
